CREATE TABLE Categories (CategoryID INT IDENTITY PRIMARY KEY, Slug NVARCHAR(80) UNIQUE NOT NULL, Name NVARCHAR(120) NOT NULL);
CREATE TABLE Molecules (MoleculeID INT IDENTITY PRIMARY KEY, Name NVARCHAR(120) NOT NULL);
CREATE TABLE Products (ProductID INT IDENTITY PRIMARY KEY, Name NVARCHAR(180) NOT NULL, CategoryID INT NOT NULL FOREIGN KEY REFERENCES Categories(CategoryID), MoleculeID INT NULL FOREIGN KEY REFERENCES Molecules(MoleculeID), Summary NVARCHAR(600), SpecPDFUrl NVARCHAR(300), ImageUrl NVARCHAR(300), IsActive BIT NOT NULL DEFAULT 1);
CREATE TABLE Doctors (DoctorID INT IDENTITY PRIMARY KEY, FullName NVARCHAR(180) NOT NULL, Email NVARCHAR(180) UNIQUE NULL, Country NVARCHAR(60), Specialty NVARCHAR(120), CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE Users (UserID INT IDENTITY PRIMARY KEY, Email NVARCHAR(180) UNIQUE NOT NULL, PasswordHash NVARCHAR(256) NOT NULL, Role NVARCHAR(40) NOT NULL DEFAULT 'viewer', CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE News (NewsID INT IDENTITY PRIMARY KEY, Title NVARCHAR(200) NOT NULL, Slug NVARCHAR(160) UNIQUE NOT NULL, Body NVARCHAR(MAX) NOT NULL, CoverImageUrl NVARCHAR(300), PublishedAt DATETIME2, IsPublished BIT NOT NULL DEFAULT 0);
CREATE TABLE Applications (ApplicationID INT IDENTITY PRIMARY KEY, JobTitle NVARCHAR(160) NOT NULL, Location NVARCHAR(120), ApplicantName NVARCHAR(180) NOT NULL, ApplicantEmail NVARCHAR(180) NOT NULL, CVUrl NVARCHAR(300), CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE ContactMessages (MessageID INT IDENTITY PRIMARY KEY, Name NVARCHAR(180) NOT NULL, Email NVARCHAR(180) NOT NULL, Body NVARCHAR(1200) NOT NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

CREATE TABLE JobPostings (
  JobID INT IDENTITY PRIMARY KEY,
  Title NVARCHAR(180) NOT NULL,
  Location NVARCHAR(120) NULL,
  Body NVARCHAR(MAX) NOT NULL,
  CoverImageUrl NVARCHAR(300) NULL,
  PublishedAt DATETIME2 NULL,
  IsPublished BIT NOT NULL DEFAULT 0
);
