-- schema.sql (alineado con Admin / Frontend)
-- Crear base de datos (ejecutar en el servidor, o usar tu herramienta)
-- CREATE DATABASE LaSanteDb; USE LaSanteDb;

CREATE TABLE Categories (
  CategoryID INT IDENTITY PRIMARY KEY,
  Slug NVARCHAR(80) UNIQUE NOT NULL,
  Name NVARCHAR(120) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Molecules (
  MoleculeID INT IDENTITY PRIMARY KEY,
  Name NVARCHAR(120) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Products (
  ProductID INT IDENTITY PRIMARY KEY,
  Name NVARCHAR(180) NOT NULL,
  SKU NVARCHAR(100) NULL,
  CategoryID INT NOT NULL,
  MoleculeID INT NULL,
  Summary NVARCHAR(600) NULL,
  Excerpt NVARCHAR(600) NULL,
  Description NVARCHAR(MAX) NULL,
  SpecPDFUrl NVARCHAR(300) NULL,
  ImageUrl NVARCHAR(300) NULL,
  TagsJson NVARCHAR(MAX) NULL, -- JSON array of tags (optional)
  Price DECIMAL(10,2) NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Products_Categories FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID) ON DELETE RESTRICT,
  CONSTRAINT FK_Products_Molecules FOREIGN KEY (MoleculeID) REFERENCES Molecules(MoleculeID) ON DELETE SET NULL
);

CREATE INDEX IX_Products_Name ON Products(Name);
CREATE INDEX IX_Products_IsActive ON Products(IsActive);

CREATE TABLE Banners (
  BannerID INT IDENTITY PRIMARY KEY,
  Title NVARCHAR(200) NULL,
  ImageUrl NVARCHAR(500) NULL,
  LinkUrl NVARCHAR(500) NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  [Order] INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE News (
  NewsID INT IDENTITY PRIMARY KEY,
  Title NVARCHAR(200) NOT NULL,
  Slug NVARCHAR(160) UNIQUE NOT NULL,
  Excerpt NVARCHAR(1000) NULL,
  Body NVARCHAR(MAX) NOT NULL,
  CoverImageUrl NVARCHAR(300) NULL,
  Author NVARCHAR(200) NULL,
  Category NVARCHAR(120) NULL,
  TagsJson NVARCHAR(MAX) NULL,
  PublishedAt DATETIME2 NULL,
  IsPublished BIT NOT NULL DEFAULT 0,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE INDEX IX_News_Slug ON News(Slug);
CREATE INDEX IX_News_IsPublished ON News(IsPublished);

CREATE TABLE JobPostings (
  JobID INT IDENTITY PRIMARY KEY,
  Title NVARCHAR(180) NOT NULL,
  Location NVARCHAR(120) NULL,
  Area NVARCHAR(120) NULL,
  Type NVARCHAR(80) NULL,
  Level NVARCHAR(80) NULL,
  ShortDescription NVARCHAR(1000) NULL,
  Body NVARCHAR(MAX) NOT NULL,
  CoverImageUrl NVARCHAR(300) NULL,
  PublishedAt DATETIME2 NULL,
  IsPublished BIT NOT NULL DEFAULT 0,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE INDEX IX_Jobs_IsPublished ON JobPostings(IsPublished);

CREATE TABLE Applications (
  ApplicationID INT IDENTITY PRIMARY KEY,
  JobID INT NULL,
  JobTitle NVARCHAR(160) NOT NULL,
  Location NVARCHAR(120) NULL,
  ApplicantName NVARCHAR(180) NOT NULL,
  ApplicantEmail NVARCHAR(180) NOT NULL,
  CvUrl NVARCHAR(500) NULL,
  Message NVARCHAR(MAX) NULL,
  SentAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Applications_Job FOREIGN KEY (JobID) REFERENCES JobPostings(JobID) ON DELETE SET NULL
);

CREATE TABLE ContactMessages (
  MessageID INT IDENTITY PRIMARY KEY,
  Name NVARCHAR(180) NOT NULL,
  Email NVARCHAR(180) NOT NULL,
  Body NVARCHAR(1200) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Users (
  UserID INT IDENTITY PRIMARY KEY,
  Email NVARCHAR(180) UNIQUE NOT NULL,
  PasswordHash NVARCHAR(512) NOT NULL,
  Role NVARCHAR(40) NOT NULL DEFAULT 'viewer',
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

-- Optional: table to store product tags normalized (if you prefer relational)
CREATE TABLE ProductTags (
  ProductTagID INT IDENTITY PRIMARY KEY,
  ProductID INT NOT NULL,
  Tag NVARCHAR(120) NOT NULL,
  CONSTRAINT FK_ProductTags_Product FOREIGN KEY (ProductID) REFERENCES Products(ProductID) ON DELETE CASCADE
);
CREATE INDEX IX_ProductTags_Tag ON ProductTags(Tag);
